import { MarketplaceListing, marketplacePhotoUrl } from './marketplace-listing';

/**
 * Sample listings seeding the prototype, spanning all six categories the
 * same way real IU Classifieds traffic does: secondhand goods, textbooks,
 * sublets, gigs, tutoring/services, and giveaways.
 */
export const MARKETPLACE_LISTINGS: MarketplaceListing[] = [
  {
    id: 'mini-fridge',
    title: 'Mini Fridge — Perfect for Dorms',
    category: 'For Sale',
    price: 60,
    condition: 'Used - good',
    description: 'Compact 3.2 cu ft fridge with small freezer compartment. Kept it clean all year, just moving out and don\'t need it over the summer. Pickup only.',
    photoUrl: marketplacePhotoUrl('mini-fridge'),
    photoIcon: 'kitchen-set',
    location: 'Bloomington — Foster Quad',
    sellerName: 'Priya N.',
    sellerEmail: 'priyan@iu.edu',
    postedDaysAgo: 1,
  },
  {
    id: 'trek-mountain-bike',
    title: 'Trek 820 Mountain Bike',
    category: 'For Sale',
    price: 120,
    condition: 'Used - fair',
    description: 'Reliable commuter bike, great for getting around campus. Tires and brakes replaced last fall. A couple of cosmetic scratches but rides smooth.',
    photoUrl: marketplacePhotoUrl('trek-mountain-bike'),
    photoIcon: 'bicycle',
    location: 'Bloomington — near Campus',
    sellerName: 'Jordan K.',
    sellerEmail: 'jordank@iu.edu',
    postedDaysAgo: 3,
  },
  {
    id: 'ikea-desk-chair',
    title: 'IKEA Desk & Chair Set',
    category: 'For Sale',
    price: 45,
    condition: 'Like new',
    description: 'White IKEA desk with matching chair, only used for one semester. Disassembles easily for transport. Great for a dorm room or apartment.',
    photoUrl: marketplacePhotoUrl('ikea-desk-chair'),
    photoIcon: 'chair',
    location: 'Indianapolis — IUPUI',
    sellerName: 'Marcus T.',
    sellerEmail: 'marcust@iu.edu',
    postedDaysAgo: 2,
  },
  {
    id: 'ps5-two-controllers',
    title: 'PS5 with Two Controllers',
    category: 'For Sale',
    price: 350,
    condition: 'Like new',
    description: 'Barely used PS5 disc edition, comes with two DualSense controllers and three games. Selling because I need the desk space more than the console.',
    photoUrl: marketplacePhotoUrl('ps5-two-controllers'),
    photoIcon: 'gamepad',
    location: 'Bloomington — Willkie Quad',
    sellerName: 'Devon W.',
    sellerEmail: 'devonw@iu.edu',
    postedDaysAgo: 5,
  },
  {
    id: 'acoustic-guitar',
    title: 'Acoustic Guitar',
    category: 'For Sale',
    price: 90,
    condition: 'Used - good',
    description: 'Yamaha acoustic guitar, great for beginners. Comes with a soft case and a spare set of strings. Just needs a new home since I switched to piano.',
    photoUrl: marketplacePhotoUrl('acoustic-guitar'),
    photoIcon: 'guitar',
    location: 'Bloomington — Ashton Center',
    sellerName: 'Sofia R.',
    sellerEmail: 'sofiar@iu.edu',
    postedDaysAgo: 6,
  },
  {
    id: 'biol-l112-textbook-bundle',
    title: 'BIOL-L 112 Textbook Bundle',
    category: 'Textbooks & Supplies',
    price: 40,
    condition: 'Used - good',
    description: 'Textbook plus lab manual for BIOL-L 112, both editions currently required. Some highlighting in the first few chapters, otherwise in great shape.',
    photoUrl: marketplacePhotoUrl('biol-l112-textbook-bundle'),
    photoIcon: 'book',
    location: 'Bloomington',
    sellerName: 'Emily C.',
    sellerEmail: 'emilyc@iu.edu',
    postedDaysAgo: 4,
  },
  {
    id: 'ti-84-calculator',
    title: 'TI-84 Plus Graphing Calculator',
    category: 'Textbooks & Supplies',
    price: 35,
    condition: 'Used - good',
    description: 'Used for two semesters of calculus, works perfectly. Comes with the original case and a fresh set of batteries.',
    photoUrl: marketplacePhotoUrl('ti-84-calculator'),
    photoIcon: 'calculator',
    location: 'Bloomington',
    sellerName: 'Aidan B.',
    sellerEmail: 'aidanb@iu.edu',
    postedDaysAgo: 8,
  },
  {
    id: 'spring-sublet-college-ave',
    title: 'Spring Sublet Near Campus (1BR)',
    category: 'Housing & Sublets',
    price: null,
    description: 'Subletting my 1-bedroom apartment for spring semester while I\'m studying abroad. Ten-minute walk to campus, utilities included, flexible move-in date.',
    photoUrl: marketplacePhotoUrl('spring-sublet-college-ave'),
    photoIcon: 'building',
    location: 'Bloomington — College Ave',
    sellerName: 'Grace L.',
    sellerEmail: 'gracel@iu.edu',
    postedDaysAgo: 2,
  },
  {
    id: 'roommate-wanted-fall',
    title: 'Roommate Wanted — Fall Semester',
    category: 'Housing & Sublets',
    price: null,
    description: 'Looking for a roommate to share a 2-bedroom near Smallwood starting in the fall. Quiet building, on the bus line, would love someone tidy and easygoing.',
    photoUrl: marketplacePhotoUrl('roommate-wanted-fall'),
    photoIcon: 'house',
    location: 'Bloomington — Smallwood',
    sellerName: 'Noah P.',
    sellerEmail: 'noahp@iu.edu',
    postedDaysAgo: 9,
  },
  {
    id: 'weekend-dog-walker',
    title: 'Weekend Dog Walker Needed',
    category: 'Jobs & Gigs',
    price: null,
    description: 'Looking for someone reliable to walk our dog on Saturday and Sunday mornings, about 30 minutes each visit. Pays $15/hr, flexible with your schedule.',
    photoUrl: marketplacePhotoUrl('weekend-dog-walker'),
    photoIcon: 'dog',
    location: 'Bloomington',
    sellerName: 'The Alvarez Family',
    sellerEmail: 'alvarezhome@iu.edu',
    postedDaysAgo: 3,
  },
  {
    id: 'barista-career-center',
    title: 'Part-Time Barista, Career Center Coffee',
    category: 'Jobs & Gigs',
    price: null,
    description: 'Campus coffee cart is hiring for the spring semester, 10-15 hours a week. No experience necessary, we\'ll train you. Great for students with morning gaps.',
    photoUrl: marketplacePhotoUrl('barista-career-center'),
    photoIcon: 'mug-hot',
    location: 'Indianapolis — IUPUI',
    sellerName: 'Career Center Coffee',
    sellerEmail: 'ccc-hiring@iu.edu',
    postedDaysAgo: 7,
  },
  {
    id: 'calc-stats-tutoring',
    title: 'Math Tutoring — Calculus & Statistics',
    category: 'Services',
    price: null,
    description: 'Grad student offering tutoring for Calc I/II and intro statistics. $25/hr, in person or over video call. Message me with your course and availability.',
    photoUrl: marketplacePhotoUrl('calc-stats-tutoring'),
    photoIcon: 'chalkboard',
    location: 'Bloomington',
    sellerName: 'Wei Z.',
    sellerEmail: 'weiz@iu.edu',
    postedDaysAgo: 4,
  },
  {
    id: 'bike-repair-tuneups',
    title: 'Bike Repair & Tune-Ups',
    category: 'Services',
    price: null,
    description: 'Former bike shop mechanic offering flat repairs, brake adjustments, and full tune-ups at a fraction of shop prices. Message me for current rates.',
    photoUrl: marketplacePhotoUrl('bike-repair-tuneups'),
    photoIcon: 'wrench',
    location: 'Bloomington',
    sellerName: 'Ben H.',
    sellerEmail: 'benh@iu.edu',
    postedDaysAgo: 10,
  },
  {
    id: 'free-couch-pickup',
    title: 'Free Couch — Must Pick Up',
    category: 'Free Stuff',
    price: 0,
    condition: 'Used - fair',
    description: 'Gray fabric couch, comfortable but showing some wear. Free to whoever can pick it up this week — I\'m moving out and it won\'t fit in the new place.',
    photoUrl: marketplacePhotoUrl('free-couch-pickup'),
    photoIcon: 'couch',
    location: 'Bloomington — Campus View Apartments',
    sellerName: 'Taylor S.',
    sellerEmail: 'taylors@iu.edu',
    postedDaysAgo: 1,
  },
  {
    id: 'free-moving-boxes',
    title: 'Free Moving Boxes',
    category: 'Free Stuff',
    price: 0,
    condition: 'Used - good',
    description: 'About 15 flattened moving boxes in decent condition, plus some bubble wrap. Just finished unpacking and would rather someone reuse them than toss them.',
    photoUrl: marketplacePhotoUrl('free-moving-boxes'),
    photoIcon: 'boxes-stacked',
    location: 'Bloomington',
    sellerName: 'Hannah M.',
    sellerEmail: 'hannahm@iu.edu',
    postedDaysAgo: 5,
  },
];
